//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GC_FinalProject_FFLTool.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FFLToolEntities2 : DbContext
    {
        public FFLToolEntities2() : base("name=FFLToolEntities2")
        {
            // Get the ObjectContext related to this DbContext
            var objectContext = (this as IObjectContextAdapter).ObjectContext;

            // Sets the command timeout for all the commands
            objectContext.CommandTimeout = 3 * 60;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<tblJsonDump> tblJsonDump { get; set; }
        public virtual DbSet<tblUserWatchlists> tblUserWatchlists { get; set; }
        public virtual DbSet<tblWatchlists> tblWatchlists { get; set; }
        public virtual DbSet<tblWeeks> tblWeeks { get; set; }
        public virtual DbSet<vwJson_MySportsFeedsData2018> vwJson_MySportsFeedsData2018 { get; set; }
        public virtual DbSet<vwMySportsFeedsData2014> vwMySportsFeedsData2014 { get; set; }
        public virtual DbSet<vwMySportsFeedsData2015> vwMySportsFeedsData2015 { get; set; }
        public virtual DbSet<vwMySportsFeedsData2016> vwMySportsFeedsData2016 { get; set; }
        public virtual DbSet<vwMySportsFeedsData2017> vwMySportsFeedsData2017 { get; set; }
        public virtual DbSet<vwMySportsFeedsData2018> vwMySportsFeedsData2018 { get; set; }
        public virtual DbSet<vwMySportsFeedsDataPlayerLogs2014> vwMySportsFeedsDataPlayerLogs2014 { get; set; }
        public virtual DbSet<vwMySportsFeedsDataPlayerLogs2015> vwMySportsFeedsDataPlayerLogs2015 { get; set; }
        public virtual DbSet<vwMySportsFeedsDataPlayerLogs2016> vwMySportsFeedsDataPlayerLogs2016 { get; set; }
        public virtual DbSet<vwMySportsFeedsDataPlayerLogs2017> vwMySportsFeedsDataPlayerLogs2017 { get; set; }
        public virtual DbSet<vwMySportsFeedsDataPlayerLogs2018> vwMySportsFeedsDataPlayerLogs2018 { get; set; }
    }
}
