//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GC_FinalProject_FFLTool.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FFLToolEntities2 : DbContext
    {
        public FFLToolEntities2()
            : base("name=FFLToolEntities2")
        {
            var objContext = (this as IObjectContextAdapter).ObjectContext;
            objContext.CommandTimeout = 60 * 5; //measured in seconds
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<tblJsonDump> tblJsonDump { get; set; }
        public virtual DbSet<tblUserWatchlists> tblUserWatchlists { get; set; }
        public virtual DbSet<tblWatchlists> tblWatchlists { get; set; }
        public virtual DbSet<tblWeeks> tblWeeks { get; set; }
    }
}
