//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GC_FinalProject_FFLTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWeeks
    {
        public int WeekId { get; set; }
        public string Season { get; set; }
        public string WeekNumber { get; set; }
        public System.DateTime WeekStart { get; set; }
        public System.DateTime WeekEnd { get; set; }
        public string WeekSuffix { get; set; }
    }
}
