// <auto-generated />
namespace GC_FinalProject_FFLTool.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class UsedbMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UsedbMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201712042006326_UsedbMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
